function SpawnRegions()
	return {
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },		
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "Blueberry", file = "media/maps/Blueberry/spawnpoints.lua" },
		{ name = "Chernaville", file = "media/maps/Chernaville/spawnpoints.lua" },
		{ name = "Chinatown", file = "media/maps/Chinatown/spawnpoints.lua" },
		{ name = "Frankfort", file = "media/maps/Frankfort/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "Greenleaf", file = "media/maps/Greenleaf/spawnpoints.lua" },
		{ name = "Kingsmouth", file = "media/maps/Kingsmouth/spawnpoints.lua" },
		{ name = "LakeIvyTownship", file = "media/maps/LakeIvyTownship/spawnpoints.lua" },
		{ name = "LittleTownship", file = "media/maps/LittleTownship/spawnpoints.lua" },
		{ name = "MarchRidgeExpansion", file = "media/maps/MarchRidgeExpansion/spawnpoints.lua" },
		{ name = "NewDenver", file = "media/maps/NewDenver/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "OldParkTown", file = "media/maps/OldParkTown/spawnpoints.lua" },
		{ name = "OldPineVillage", file = "media/maps/OldPineVillage/spawnpoints.lua" },
		{ name = "OverTheRiver", file = "media/maps/OverTheRiver/spawnpoints.lua" },
		{ name = "Pitstop", file = "media/maps/Pitstop/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "Refordville", file = "media/maps/Refordville/spawnpoints.lua" },
		{ name = "Rosebery", file = "media/maps/Rosebery/spawnpoints.lua" },
		{ name = "RosewoodExpansion", file = "media/maps/RosewoodExpansion/spawnpoints.lua" },
		{ name = "Sanctuary", file = "media/maps/Sanctuary/spawnpoints.lua" },		
		{ name = "Silverton", file = "media/maps/Silverton/spawnpoints.lua" },
		{ name = "Tugaland", file = "media/maps/Tugaland/spawnpoints.lua" },
		{ name = "Wildberries", file = "media/maps/Wildberries/spawnpoints.lua" },
	}
end
