-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["LargeFreezer_01_0"] = {{ name = "other", tiles = {"LargeFreezer_01_4", "LargeFreezer_01_8"} }, { name = "other", tiles = {"LargeFreezer_01_4", "LargeFreezer_01_8"} }}
overlayMap["LargeFreezer_01_1"] = {{ name = "other", tiles = {"LargeFreezer_01_5", "LargeFreezer_01_9"} }, { name = "other", tiles = {"LargeFreezer_01_5", "LargeFreezer_01_9"} }}
overlayMap["LargeFreezer_01_2"] = {{ name = "other", tiles = {"LargeFreezer_01_6", "LargeFreezer_01_10"} }, { name = "other", tiles = {"LargeFreezer_01_6", "LargeFreezer_01_10"} }}
overlayMap["LargeFreezer_01_3"] = {{ name = "other", tiles = {"LargeFreezer_01_7", "LargeFreezer_01_11"} }, { name = "other", tiles = {"LargeFreezer_01_7", "LargeFreezer_01_11"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
