-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1

--[[ Chinatown Tiles ]]
overlayMap["Guizi_tiles_01_0"] = {{ name = "armystorage", tiles = {"Guizi_tiles_01_13", "Guizi_tiles_01_12"} }, { name = "other", tiles = {"Guizi_tiles_01_4", "Guizi_tiles_01_2"} }}
overlayMap["Guizi_tiles_01_1"] = {{ name = "armystorage", tiles = {"Guizi_tiles_01_15", "Guizi_tiles_01_14"} }, { name = "other", tiles = {"Guizi_tiles_01_5", "Guizi_tiles_01_3"} }}
overlayMap["Guizi_tiles_01_6"] = {{ name = "armystorage", tiles = {"Guizi_tiles_01_17", "Guizi_tiles_01_16"} }, { name = "other", tiles = {"Guizi_tiles_01_11", "Guizi_tiles_01_9"} }}
overlayMap["Guizi_tiles_01_7"] = {{ name = "armystorage", tiles = {"Guizi_tiles_01_19", "Guizi_tiles_01_18"} }, { name = "other", tiles = {"Guizi_tiles_01_10", "Guizi_tiles_01_8"} }}
overlayMap["Industry_3_4"] = {{ name = "other", tiles = {"Industry_3_6", "Industry_3_6"} }}
overlayMap["Industry_3_5"] = {{ name = "other", tiles = {"Industry_3_7", "Industry_3_7"} }}

--[[ Daddy Diederik's Tiles ]]
overlayMap["d_furniture_bedroom_01_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_01_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_02_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_02_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_03_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_03_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_04_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_04_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_05_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_05_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_storage_ddd_01_0"] = {{ name = "other", tiles = {"container_overlays_ddd_01_8", "container_overlays_ddd_01_0"} }}
overlayMap["furniture_storage_ddd_01_1"] = {{ name = "other", tiles = {"container_overlays_ddd_01_9", "container_overlays_ddd_01_1"} }}
overlayMap["furniture_storage_ddd_01_2"] = {{ name = "other", tiles = {"container_overlays_ddd_01_10", "container_overlays_ddd_01_2"} }}
overlayMap["furniture_storage_ddd_01_3"] = {{ name = "other", tiles = {"container_overlays_ddd_01_11", "container_overlays_ddd_01_3"} }}
overlayMap["furniture_storage_ddd_01_12"] = {{ name = "other", tiles = {"container_overlays_ddd_01_40", "container_overlays_ddd_01_32"} }}
overlayMap["furniture_storage_ddd_01_14"] = {{ name = "other", tiles = {"books&misc_01_24", "books&misc_01_28"} }}
overlayMap["furniture_storage_ddd_01_15"] = {{ name = "other", tiles = {"books&misc_01_27", "books&misc_01_28"} }}
overlayMap["furniture_storage_ddd_01_24"] = {{ name = "other", tiles = {"container_overlays_ddd_01_24", "container_overlays_ddd_01_16"} }}
overlayMap["furniture_storage_ddd_01_25"] = {{ name = "other", tiles = {"container_overlays_ddd_01_25", "container_overlays_ddd_01_17"} }}
overlayMap["furniture_storage_ddd_01_26"] = {{ name = "other", tiles = {"container_overlays_ddd_01_26", "container_overlays_ddd_01_18"} }}
overlayMap["furniture_storage_ddd_01_27"] = {{ name = "other", tiles = {"container_overlays_ddd_01_27", "container_overlays_ddd_01_19"} }}
overlayMap["furniture_storage_ddd_01_48"] = {{ name = "other", tiles = {"container_overlays_ddd_01_60", "container_overlays_ddd_01_60"} }}
overlayMap["furniture_storage_ddd_01_51"] = {{ name = "other", tiles = {"container_overlays_ddd_01_59", "container_overlays_ddd_01_59"} }}
overlayMap["furniture_storage_ddd_01_53"] = {{ name = "other", tiles = {"container_overlays_ddd_01_61", "container_overlays_ddd_01_61"} }}
overlayMap["furniture_storage_ddd_01_54"] = {{ name = "other", tiles = {"container_overlays_ddd_01_62", "container_overlays_ddd_01_62"} }}
overlayMap["furniture_storage_ddd_01_55"] = {{ name = "other", tiles = {"container_overlays_ddd_01_63", "container_overlays_ddd_01_63"} }}
overlayMap["industry_dirkea_ddd_01_12"] = {{ name = "other", tiles = {"container_overlays_ddd_01_12", "container_overlays_ddd_01_4"} }}
overlayMap["industry_dirkea_ddd_01_13"] = {{ name = "other", tiles = {"container_overlays_ddd_01_13", "container_overlays_ddd_01_5"} }}
overlayMap["industry_dirkea_ddd_01_14"] = {{ name = "other", tiles = {"container_overlays_ddd_01_6", "container_overlays_ddd_01_14"} }}
overlayMap["industry_dirkea_ddd_01_15"] = {{ name = "other", tiles = {"container_overlays_ddd_01_7", "container_overlays_ddd_01_15"} }}
overlayMap["industry_dirkea_ddd_01_24"] = {{ name = "other", tiles = {"container_overlays_ddd_01_20", "container_overlays_ddd_01_20"} }, { name = "other", tiles = {"container_overlays_ddd_01_28", "container_overlays_ddd_01_28"} }}
overlayMap["industry_dirkea_ddd_01_25"] = {{ name = "other", tiles = {"container_overlays_ddd_01_21", "container_overlays_ddd_01_21"} }, { name = "other", tiles = {"container_overlays_ddd_01_29", "container_overlays_ddd_01_29"} }}
overlayMap["industry_dirkea_ddd_01_26"] = {{ name = "other", tiles = {"container_overlays_ddd_01_22", "container_overlays_ddd_01_22"} }, { name = "other", tiles = {"container_overlays_ddd_01_30", "container_overlays_ddd_01_30"} }}
overlayMap["industry_dirkea_ddd_01_27"] = {{ name = "other", tiles = {"container_overlays_ddd_01_23", "container_overlays_ddd_01_23"} }, { name = "other", tiles = {"container_overlays_ddd_01_31", "container_overlays_ddd_01_31"} }}
overlayMap["industry_dirkea_ddd_01_37"] = {{ name = "other", tiles = {"container_overlays_ddd_01_36", "container_overlays_ddd_01_44"} }, { name = "other", tiles = {"container_overlays_ddd_01_37", "container_overlays_ddd_01_45"} }}
overlayMap["industry_dirkea_ddd_01_38"] = {{ name = "other", tiles = {"container_overlays_ddd_01_38", "container_overlays_ddd_01_46"} }, { name = "other", tiles = {"container_overlays_ddd_01_39", "container_overlays_ddd_01_47"} }}
overlayMap["industry_railroad_ddd_01_28"] = {{ name = "other", tiles = {"container_overlays_ddd_01_54", "container_overlays_ddd_01_54"} }}
overlayMap["industry_railroad_ddd_01_29"] = {{ name = "other", tiles = {"container_overlays_ddd_01_55", "container_overlays_ddd_01_55"} }}
overlayMap["industry_railroad_ddd_01_36"] = {{ name = "other", tiles = {"container_overlays_ddd_01_52", "container_overlays_ddd_01_52"} }}
overlayMap["industry_railroad_ddd_01_37"] = {{ name = "other", tiles = {"container_overlays_ddd_01_53", "container_overlays_ddd_01_53"} }}

--[[ Damiao Tiles ]]
overlayMap["damiao_sign_01_16"] = {{ name = "other", tiles = {"damiao_sign_01_17"} }}
overlayMap["damiao_sign_01_19"] = {{ name = "other", tiles = {"damiao_sign_01_18"} }}
overlayMap["damiao_club_01_1"] = {{ name = "other", tiles = {"damiao_club_01_2"} }}
overlayMap["damiao_club_01_4"] = {{ name = "other", tiles = {"damiao_club_01_3"} }}
overlayMap["damiao_club_01_8"] = {{ name = "other", tiles = {"damiao_club_01_9"} }}
overlayMap["damiao_club_01_11"] = {{ name = "other", tiles = {"damiao_club_01_10"} }}
overlayMap["damiao_club_01_12"] = {{ name = "other", tiles = {"damiao_club_01_13"} }}
overlayMap["damiao_club_01_15"] = {{ name = "other", tiles = {"damiao_club_01_14"} }}
overlayMap["damiao_club_01_56"] = {{ name = "other", tiles = {"damiao_club_01_58"} }}
overlayMap["damiao_club_01_57"] = {{ name = "other", tiles = {"damiao_club_01_59"} }}
overlayMap["damiao_tile_01_0"] = {{ name = "other", tiles = {"damiao_tile_01_1"} }}
overlayMap["damiao_tile_01_3"] = {{ name = "other", tiles = {"damiao_tile_01_2"} }}
overlayMap["damiao_tile_01_7"] = {{ name = "other", tiles = {"damiao_tile_01_6"} }}
overlayMap["damiao_tile_01_4"] = {{ name = "other", tiles = {"damiao_tile_01_5"} }}
overlayMap["damiao_tile_01_8"] = {{ name = "other", tiles = {"damiao_tile_01_10"} }}
overlayMap["damiao_tile_01_9"] = {{ name = "other", tiles = {"damiao_tile_01_11"} }}
overlayMap["damiao_tile_01_16"] = {{ name = "other", tiles = {"damiao_tile_01_17"} }}
overlayMap["damiao_tile_01_19"] = {{ name = "other", tiles = {"damiao_tile_01_18"} }}
overlayMap["damiao_tile_01_20"] = {{ name = "other", tiles = {"damiao_tile_01_21"} }}
overlayMap["damiao_tile_01_23"] = {{ name = "other", tiles = {"damiao_tile_01_22"} }}
overlayMap["damiao_tile_02_27"] = {{ name = "other", tiles = {"damiao_tile_02_28"} }}
overlayMap["damiao_tile_02_30"] = {{ name = "other", tiles = {"damiao_tile_02_29"} }}
overlayMap["damiao_tile_02_34"] = {{ name = "other", tiles = {"damiao_tile_02_35"} }}
overlayMap["damiao_tile_02_45"] = {{ name = "other", tiles = {"damiao_tile_02_46"} }}
overlayMap["damiao_tile_02_48"] = {{ name = "other", tiles = {"damiao_tile_02_49"} }}
overlayMap["damiao_tile_02_50"] = {{ name = "other", tiles = {"damiao_tile_02_51"} }}
overlayMap["damiao_tile_02_53"] = {{ name = "other", tiles = {"damiao_tile_02_52"} }}

--[[ Dylan's Tiles ]]
overlayMap["AuthenticZ_Store_12"] = {{ name = "other", tiles = {"AuthenticZ_Store_8", "AuthenticZ_Store_10"} }}
overlayMap["AuthenticZ_Store_13"] = {{ name = "other", tiles = {"AuthenticZ_Store_9", "AuthenticZ_Store_11"} }}
overlayMap["AuthenticZ_Store_16"] = {{ name = "other", tiles = {"AuthenticZ_Store_18", "AuthenticZ_Store_18"} }}
overlayMap["AuthenticZ_Store_17"] = {{ name = "other", tiles = {"AuthenticZ_Store_19", "AuthenticZ_Store_19"} }}
overlayMap["AuthenticZ_Store_25"] = {{ name = "other", tiles = {"clothing_01_11", "clothing_01_19"} }}
overlayMap["AuthenticZ_Store_26"] = {{ name = "other", tiles = {"clothing_01_12", "clothing_01_20"} }}
overlayMap["AuthenticZ_Store_27"] = {{ name = "other", tiles = {"clothing_01_13", "clothing_01_21"} }}
overlayMap["AuthenticZ_Store_36"] = {{ name = "other", tiles = {"AuthenticZ_Store_32", "AuthenticZ_Store_34"} }}
overlayMap["AuthenticZ_Store_37"] = {{ name = "other", tiles = {"AuthenticZ_Store_33", "AuthenticZ_Store_35"} }}
overlayMap["Block_Trasher_0"] = {{ name = "other", tiles = {"Block_Trasher_8", "Block_Trasher_12"} }}
overlayMap["Block_Trasher_1"] = {{ name = "other", tiles = {"Block_Trasher_9", "Block_Trasher_13"} }}
overlayMap["Block_Trasher_2"] = {{ name = "other", tiles = {"Block_Trasher_10", "Block_Trasher_14"} }}
overlayMap["Block_Trasher_3"] = {{ name = "other", tiles = {"Block_Trasher_11", "Block_Trasher_15"} }}
overlayMap["Block_Trasher_24"] = {{ name = "other", tiles = {"food_01_0", "food_01_2"} }}
overlayMap["Block_Trasher_25"] = {{ name = "other", tiles = {"food_01_1", "food_01_3"} }}
overlayMap["Block_Trasher_40"] = {{ name = "other", tiles = {"food_02_8", "food_02_16"} }}
overlayMap["Block_Trasher_41"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["Block_Trasher_42"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["Block_Trasher_43"] = {{ name = "other", tiles = {"food_02_10", "food_02_18"} }}
overlayMap["Block_Trasher_44"] = {{ name = "other", tiles = {"food_02_11", "food_02_19"} }}
overlayMap["Block_Trasher_45"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["Block_Trasher_46"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["Block_Trasher_47"] = {{ name = "other", tiles = {"food_02_13", "food_02_21"} }}
overlayMap["Block_Trasher_60"] = {{ name = "other", tiles = {"Block_Trasher_56", "Block_Trasher_56"} }}
overlayMap["Block_Trasher_61"] = {{ name = "other", tiles = {"Block_Trasher_57", "Block_Trasher_57"} }}
overlayMap["Block_Trasher_62"] = {{ name = "other", tiles = {"Block_Trasher_58", "Block_Trasher_58"} }}
overlayMap["Block_Trasher_63"] = {{ name = "other", tiles = {"Block_Trasher_59", "Block_Trasher_59"} }}
overlayMap["Bookies_Store_12"] = {{ name = "other", tiles = {"Bookies_Store_8", "Bookies_Store_10"} }}
overlayMap["Bookies_Store_13"] = {{ name = "other", tiles = {"Bookies_Store_9", "Bookies_Store_11"} }}
overlayMap["Bookies_Store_14"] = {{ name = "other", tiles = {"Bookies_Store_18", "Bookies_Store_16"} }}
overlayMap["Bookies_Store_15"] = {{ name = "other", tiles = {"Bookies_Store_19", "Bookies_Store_17"} }}
overlayMap["Bookies_Store_22"] = {{ name = "other", tiles = {"Bookies_Store_20", "Bookies_Store_20"} }}
overlayMap["Bookies_Store_23"] = {{ name = "other", tiles = {"Bookies_Store_21", "Bookies_Store_21"} }}
overlayMap["Bookies_Store_26"] = {{ name = "other", tiles = {"Bookies_Store_24", "Bookies_Store_24"} }}
overlayMap["Bookies_Store_27"] = {{ name = "other", tiles = {"Bookies_Store_25", "Bookies_Store_25"} }}
overlayMap["Bookies_Store_30"] = {{ name = "other", tiles = {"Bookies_Store_28", "Bookies_Store_28"} }}
overlayMap["Bookies_Store_31"] = {{ name = "other", tiles = {"Bookies_Store_29", "Bookies_Store_29"} }}
overlayMap["Bookies_Store_38"] = {{ name = "other", tiles = {"Bookies_Store_28", "Bookies_Store_28"} }}
overlayMap["Bookies_Store_39"] = {{ name = "other", tiles = {"Bookies_Store_29", "Bookies_Store_29"} }}
overlayMap["Bookies_Store_42"] = {{ name = "other", tiles = {"Bookies_Store_40", "Bookies_Store_40"} }}
overlayMap["Bookies_Store_43"] = {{ name = "other", tiles = {"Bookies_Store_41", "Bookies_Store_41"} }}
overlayMap["Bookies_Store_44"] = {{ name = "other", tiles = {"Bookies_Store_48", "Bookies_Store_52"} }}
overlayMap["Bookies_Store_45"] = {{ name = "other", tiles = {"Bookies_Store_49", "Bookies_Store_53"} }}
overlayMap["Bookies_Store_46"] = {{ name = "other", tiles = {"Bookies_Store_50", "Bookies_Store_54"} }}
overlayMap["Bookies_Store_47"] = {{ name = "other", tiles = {"Bookies_Store_51", "Bookies_Store_55"} }}
overlayMap["Bookies_Store_60"] = {{ name = "other", tiles = {"Bookies_Store_56", "Bookies_Store_58"} }}
overlayMap["Bookies_Store_61"] = {{ name = "other", tiles = {"Bookies_Store_57", "Bookies_Store_59"} }}
overlayMap["DylansMusicStore_21"] = {{ name = "other", tiles = {"DylansMusicStore_9", "DylansMusicStore_13"} }}
overlayMap["DylansMusicStore_22"] = {{ name = "other", tiles = {"DylansMusicStore_10", "DylansMusicStore_14"} }}
overlayMap["DylansMusicStore_23"] = {{ name = "other", tiles = {"DylansMusicStore_11", "DylansMusicStore_15"} }}
overlayMap["DylansMusicStore_28"] = {{ name = "other", tiles = {"DylansMusicStore_24", "DylansMusicStore_26"} }}
overlayMap["DylansMusicStore_29"] = {{ name = "other", tiles = {"DylansMusicStore_25", "DylansMusicStore_27"} }}
overlayMap["DylansRandomFurniture03_54"] = {{ name = "other", tiles = {"DylansRandomFurniture03_52", "DylansRandomFurniture03_52"} }}
overlayMap["DylansRandomFurniture03_55"] = {{ name = "other", tiles = {"DylansRandomFurniture03_53", "DylansRandomFurniture03_53"} }}
overlayMap["DylansRandomFurniture03_60"] = {{ name = "other", tiles = {"DylansRandomFurniture03_62", "DylansRandomFurniture03_62"} }}
overlayMap["DylansRandomFurniture03_61"] = {{ name = "other", tiles = {"DylansRandomFurniture03_63", "DylansRandomFurniture03_63"} }}
overlayMap["DylansRandomFurniture04_13"] = {{ name = "other", tiles = {"DylansRandomFurniture04_12", "DylansRandomFurniture04_12"} }}
overlayMap["DylansRandomFurniture04_15"] = {{ name = "other", tiles = {"DylansRandomFurniture04_14", "DylansRandomFurniture04_14"} }}
overlayMap["DylansRandomFurniture04_17"] = {{ name = "other", tiles = {"DylansRandomFurniture04_16", "DylansRandomFurniture04_16"} }}
overlayMap["DylansRandomFurniture04_19"] = {{ name = "other", tiles = {"DylansRandomFurniture04_18", "DylansRandomFurniture04_18"} }}
overlayMap["DylansRandomFurniture04_25"] = {{ name = "other", tiles = {"DylansRandomFurniture04_24", "DylansRandomFurniture04_24"} }}
overlayMap["DylansRandomFurniture04_26"] = {{ name = "other", tiles = {"DylansRandomFurniture04_27", "DylansRandomFurniture04_27"} }}
overlayMap["Obs_02_6"] = {{ name = "other", tiles = {"Obs_02_7", "Obs_02_7"} }}
overlayMap["Obs_02_29"] = {{ name = "other", tiles = {"Obs_02_30", "Obs_02_30"} }}
overlayMap["Obs_02_54"] = {{ name = "other", tiles = {"Obs_02_52", "Obs_02_52"} }}
overlayMap["Obs_02_55"] = {{ name = "other", tiles = {"Obs_02_53", "Obs_02_53"} }}
overlayMap["Obs_03_0"] = {{ name = "other", tiles = {"Obs_03_3", "Obs_03_3"} }}
overlayMap["Obs_03_1"] = {{ name = "other", tiles = {"Obs_03_4", "Obs_03_4"} }}
overlayMap["Obs_03_2"] = {{ name = "other", tiles = {"Obs_03_5", "Obs_03_5"} }}
overlayMap["Obs_03_12"] = {{ name = "other", tiles = {"Obs_03_11", "Obs_03_11"} }}
overlayMap["Obs_03_13"] = {{ name = "other", tiles = {"Obs_03_14"} }}
overlayMap["Obs_03_16"] = {{ name = "other", tiles = {"Obs_03_19", "Obs_03_19"} }}
overlayMap["Obs_03_17"] = {{ name = "other", tiles = {"Obs_03_20", "Obs_03_20"} }}
overlayMap["Obs_03_18"] = {{ name = "other", tiles = {"Obs_03_21", "Obs_03_21"} }}
overlayMap["Obs_03_22"] = {{ name = "other", tiles = {"Obs_03_23", "Obs_03_23"} }}
overlayMap["Obs_03_24"] = {{ name = "other", tiles = {"Obs_03_28", "Obs_03_28"} }}
overlayMap["Obs_03_25"] = {{ name = "other", tiles = {"Obs_03_29", "Obs_03_29"} }}
overlayMap["Obs_03_26"] = {{ name = "other", tiles = {"Obs_03_30", "Obs_03_30"} }}
overlayMap["Obs_03_27"] = {{ name = "other", tiles = {"Obs_03_31", "Obs_03_31"} }}
overlayMap["Obs_03_34"] = {{ name = "other", tiles = {"Obs_03_33", "Obs_03_33"} }}
overlayMap["Obs_03_36"] = {{ name = "other", tiles = {"Obs_03_35", "Obs_03_35"} }}
overlayMap["Obs_04_0"] = {{ name = "other", tiles = {"Obs_04_8", "Obs_04_8"} }}
overlayMap["Obs_04_1"] = {{ name = "other", tiles = {"Obs_04_9", "Obs_04_9"} }}
overlayMap["Obs_04_2"] = {{ name = "other", tiles = {"Obs_04_10", "Obs_04_10"} }}
overlayMap["Obs_04_3"] = {{ name = "other", tiles = {"Obs_04_11", "Obs_04_11"} }}
overlayMap["Obs_04_4"] = {{ name = "other", tiles = {"Obs_04_12", "Obs_04_12"} }}
overlayMap["Obs_04_5"] = {{ name = "other", tiles = {"Obs_04_6", "Obs_04_6"} }}

--[[ New Ekron Tiles ]]
overlayMap["Ekron02_8"] = {{ name = "other", tiles = {"Ekron02_0", "Ekron02_0"} }}
overlayMap["Ekron02_24"] = {{ name = "other", tiles = {"Ekron02_25", "Ekron02_25"} }}

--[[ Throttle Kitty's Tiles ]]
overlayMap["industry_tk_02_25"] = {{ name = "other", tiles = {"container_overlays_tk_01_0", "container_overlays_tk_01_0"} }}
overlayMap["industry_tk_02_26"] = {{ name = "other", tiles = {"container_overlays_tk_01_1", "container_overlays_tk_01_1"} }}
overlayMap["trash_containers_tk_01_2"] = {{ name = "other", tiles = {"container_overlays_tk_02_25", "container_overlays_tk_02_24"} }}
overlayMap["trash_containers_tk_01_3"] = {{ name = "other", tiles = {"container_overlays_tk_02_27", "container_overlays_tk_02_26"} }}
overlayMap["trash_containers_tk_01_4"] = {{ name = "kitchen", tiles = {"container_overlays_tk_02_33", "container_overlays_tk_02_32"} }, { name = "other", tiles = {"container_overlays_tk_02_36", "container_overlays_tk_02_36"} }}
overlayMap["trash_containers_tk_01_5"] = {{ name = "kitchen", tiles = {"container_overlays_tk_02_35", "container_overlays_tk_02_34"} }, { name = "other", tiles = {"container_overlays_tk_02_37", "container_overlays_tk_02_37"} }}
overlayMap["trash_containers_tk_01_6"] = {{ name = "kitchen", tiles = {"container_overlays_tk_02_33", "container_overlays_tk_02_32"} }, { name = "other", tiles = {"container_overlays_tk_02_36", "container_overlays_tk_02_36"} }}
overlayMap["trash_containers_tk_01_7"] = {{ name = "kitchen", tiles = {"container_overlays_tk_02_35", "container_overlays_tk_02_34"} }, { name = "other", tiles = {"container_overlays_tk_02_37", "container_overlays_tk_02_37"} }}
overlayMap["trash_containers_tk_01_8"] = {{ name = "other", tiles = {"container_overlays_tk_02_9", "container_overlays_tk_02_8"} }}
overlayMap["trash_containers_tk_01_9"] = {{ name = "other", tiles = {"container_overlays_tk_02_11", "container_overlays_tk_02_10"} }}
overlayMap["trash_containers_tk_01_16"] = {{ name = "other", tiles = {"container_overlays_tk_02_16", "container_overlays_tk_02_0"} }}
overlayMap["trash_containers_tk_01_17"] = {{ name = "other", tiles = {"container_overlays_tk_02_17", "container_overlays_tk_02_1"} }}
overlayMap["trash_containers_tk_01_18"] = {{ name = "other", tiles = {"container_overlays_tk_02_18", "container_overlays_tk_02_2"} }}
overlayMap["trash_containers_tk_01_19"] = {{ name = "other", tiles = {"container_overlays_tk_02_19", "container_overlays_tk_02_3"} }}
overlayMap["trash_containers_tk_01_20"] = {{ name = "other", tiles = {"container_overlays_tk_02_20", "container_overlays_tk_02_4"} }}
overlayMap["trash_containers_tk_01_21"] = {{ name = "other", tiles = {"container_overlays_tk_02_21", "container_overlays_tk_02_5"} }}
overlayMap["trash_containers_tk_01_22"] = {{ name = "other", tiles = {"container_overlays_tk_02_22", "container_overlays_tk_02_6"} }}
overlayMap["trash_containers_tk_01_23"] = {{ name = "other", tiles = {"container_overlays_tk_02_23", "container_overlays_tk_02_7"} }}
overlayMap["trash_containers_tk_01_24"] = {{ name = "other", tiles = {"container_overlays_tk_02_16", "container_overlays_tk_02_0"} }}
overlayMap["trash_containers_tk_01_25"] = {{ name = "other", tiles = {"container_overlays_tk_02_17", "container_overlays_tk_02_1"} }}
overlayMap["trash_containers_tk_01_26"] = {{ name = "other", tiles = {"container_overlays_tk_02_18", "container_overlays_tk_02_2"} }}
overlayMap["trash_containers_tk_01_27"] = {{ name = "other", tiles = {"container_overlays_tk_02_19", "container_overlays_tk_02_3"} }}
overlayMap["trash_containers_tk_01_28"] = {{ name = "other", tiles = {"container_overlays_tk_02_28", "container_overlays_tk_02_12"} }}
overlayMap["trash_containers_tk_01_29"] = {{ name = "other", tiles = {"container_overlays_tk_02_29", "container_overlays_tk_02_13"} }}
overlayMap["trash_containers_tk_01_30"] = {{ name = "other", tiles = {"container_overlays_tk_02_30", "container_overlays_tk_02_14"} }}
overlayMap["trash_containers_tk_01_31"] = {{ name = "other", tiles = {"container_overlays_tk_02_31", "container_overlays_tk_02_15"} }}
overlayMap["trash_containers_tk_01_40"] = {{ name = "other", tiles = {"container_overlays_tk_02_16", "container_overlays_tk_02_0"} }}
overlayMap["trash_containers_tk_01_41"] = {{ name = "other", tiles = {"container_overlays_tk_02_17", "container_overlays_tk_02_1"} }}
overlayMap["trash_containers_tk_01_42"] = {{ name = "other", tiles = {"container_overlays_tk_02_18", "container_overlays_tk_02_2"} }}
overlayMap["trash_containers_tk_01_43"] = {{ name = "other", tiles = {"container_overlays_tk_02_19", "container_overlays_tk_02_3"} }}
overlayMap["trash_containers_tk_01_44"] = {{ name = "other", tiles = {"container_overlays_tk_02_20", "container_overlays_tk_02_4"} }}
overlayMap["trash_containers_tk_01_45"] = {{ name = "other", tiles = {"container_overlays_tk_02_21", "container_overlays_tk_02_5"} }}
overlayMap["trash_containers_tk_01_46"] = {{ name = "other", tiles = {"container_overlays_tk_02_22", "container_overlays_tk_02_6"} }}
overlayMap["trash_containers_tk_01_47"] = {{ name = "other", tiles = {"container_overlays_tk_02_23", "container_overlays_tk_02_7"} }}
overlayMap["trash_containers_tk_01_48"] = {{ name = "other", tiles = {"container_overlays_tk_02_16", "container_overlays_tk_02_0"} }}
overlayMap["trash_containers_tk_01_49"] = {{ name = "other", tiles = {"container_overlays_tk_02_17", "container_overlays_tk_02_1"} }}
overlayMap["trash_containers_tk_01_50"] = {{ name = "other", tiles = {"container_overlays_tk_02_18", "container_overlays_tk_02_2"} }}
overlayMap["trash_containers_tk_01_51"] = {{ name = "other", tiles = {"container_overlays_tk_02_19", "container_overlays_tk_02_3"} }}
overlayMap["trash_containers_tk_01_52"] = {{ name = "other", tiles = {"container_overlays_tk_02_28", "container_overlays_tk_02_12"} }}
overlayMap["trash_containers_tk_01_53"] = {{ name = "other", tiles = {"container_overlays_tk_02_29", "container_overlays_tk_02_13"} }}
overlayMap["trash_containers_tk_01_54"] = {{ name = "other", tiles = {"container_overlays_tk_02_30", "container_overlays_tk_02_14"} }}
overlayMap["trash_containers_tk_01_55"] = {{ name = "other", tiles = {"container_overlays_tk_02_31", "container_overlays_tk_02_15"} }}

--[[ Western Scrap Car Yard Tiles ]]
overlayMap["LargeFreezer_01_0"] = {{ name = "other", tiles = {"LargeFreezer_01_4", "LargeFreezer_01_8"} }, { name = "other", tiles = {"LargeFreezer_01_4", "LargeFreezer_01_8"} }}
overlayMap["LargeFreezer_01_1"] = {{ name = "other", tiles = {"LargeFreezer_01_5", "LargeFreezer_01_9"} }, { name = "other", tiles = {"LargeFreezer_01_5", "LargeFreezer_01_9"} }}
overlayMap["LargeFreezer_01_2"] = {{ name = "other", tiles = {"LargeFreezer_01_6", "LargeFreezer_01_10"} }, { name = "other", tiles = {"LargeFreezer_01_6", "LargeFreezer_01_10"} }}
overlayMap["LargeFreezer_01_3"] = {{ name = "other", tiles = {"LargeFreezer_01_7", "LargeFreezer_01_11"} }, { name = "other", tiles = {"LargeFreezer_01_7", "LargeFreezer_01_11"} }}

--[[ Fort Redstone ]]
overlayMap["Union_Pallets_01_0"] = {{ name = "other", tiles = {"Union_Filler_01_0", "Union_Filler_01_0"} }}
overlayMap["Union_Pallets_01_1"] = {{ name = "other", tiles = {"Union_Filler_01_1"} }}
overlayMap["Union_Pallets_01_2"] = {{ name = "other", tiles = {"Union_Filler_01_2"} }}
overlayMap["Union_Pallets_01_3"] = {{ name = "other", tiles = {"Union_Filler_01_3"} }}
overlayMap["Union_Pallets_01_4"] = {{ name = "other", tiles = {"Union_Filler_01_4"} }}
overlayMap["Union_Pallets_01_5"] = {{ name = "other", tiles = {"Union_Filler_01_5"} }}
overlayMap["Union_Pallets_01_6"] = {{ name = "other", tiles = {"Union_Filler_01_6"} }}
overlayMap["Union_Pallets_01_7"] = {{ name = "other", tiles = {"Union_Filler_01_7"} }}
overlayMap["Union_Pallets_01_8"] = {{ name = "other", tiles = {"Union_Filler_01_8"} }}
overlayMap["Union_Pallets_01_9"] = {{ name = "other", tiles = {"Union_Filler_01_9"} }}
overlayMap["Union_Pallets_01_10"] = {{ name = "other", tiles = {"Union_Filler_01_10", "Union_Filler_01_10"} }}
overlayMap["Union_Pallets_01_11"] = {{ name = "other", tiles = {"Union_Filler_01_11", "Union_Filler_01_11"} }}
overlayMap["Union_Pallets_01_12"] = {{ name = "other", tiles = {"Union_Filler_01_12", "Union_Filler_01_12"} }}
overlayMap["Union_Pallets_01_13"] = {{ name = "other", tiles = {"Union_Filler_01_13", "Union_Filler_01_13"} }}
overlayMap["Union_Pallets_01_14"] = {{ name = "other", tiles = {"Union_Filler_01_14", "Union_Filler_01_14"} }}
overlayMap["Union_Pallets_01_15"] = {{ name = "other", tiles = {"Union_Filler_01_15", "Union_Filler_01_15"} }}

--[[ Big Zombie Monkey's ]]
overlayMap["BZM_A_SeaFood_48"] = {{ name = "other", tiles = {"BZM_A_SeaFood_52", "BZM_A_SeaFood_56"} }}
overlayMap["BZM_A_SeaFood_49"] = {{ name = "other", tiles = {"BZM_A_SeaFood_53", "BZM_A_SeaFood_57"} }}
overlayMap["BZM_A_SeaFood_50"] = {{ name = "other", tiles = {"BZM_A_SeaFood_54", "BZM_A_SeaFood_58"} }}
overlayMap["BZM_A_SeaFood_51"] = {{ name = "other", tiles = {"BZM_A_SeaFood_55", "BZM_A_SeaFood_59"} }}
overlayMap["BZM_A_SeaFood_60"] = {{ name = "other", tiles = {"BZM_A_SeaFood_12", "BZM_A_SeaFood_12"} }}
overlayMap["BZM_A_SeaFood_61"] = {{ name = "other", tiles = {"BZM_A_SeaFood_13", "BZM_A_SeaFood_13"} }}
overlayMap["BZM_A_SeaFood_62"] = {{ name = "other", tiles = {"BZM_A_SeaFood_6", "BZM_A_SeaFood_6"} }}
overlayMap["BZM_A_SeaFood_63"] = {{ name = "other", tiles = {"BZM_A_SeaFood_7", "BZM_A_SeaFood_7"} }}
overlayMap["BZM_Arcade_BERT_01_16"] = {{ name = "other", tiles = {"BZM_Arcade_BERT_01_24", "BZM_Arcade_BERT_01_32"} }}
overlayMap["BZM_Arcade_BERT_01_17"] = {{ name = "other", tiles = {"BZM_Arcade_BERT_01_25", "BZM_Arcade_BERT_01_33"} }}
overlayMap["BZM_Arcade_BERT_01_18"] = {{ name = "other", tiles = {"BZM_Arcade_BERT_01_26", "BZM_Arcade_BERT_01_34"} }}
overlayMap["BZM_Arcade_BERT_01_19"] = {{ name = "other", tiles = {"BZM_Arcade_BERT_01_27", "BZM_Arcade_BERT_01_35"} }}
overlayMap["BZM_Arcade_BERT_01_20"] = {{ name = "other", tiles = {"BZM_Arcade_BERT_01_28", "BZM_Arcade_BERT_01_36"} }}
overlayMap["BZM_Arcade_BERT_01_21"] = {{ name = "other", tiles = {"BZM_Arcade_BERT_01_29", "BZM_Arcade_BERT_01_37"} }}
overlayMap["BZM_Arcade_BERT_01_22"] = {{ name = "other", tiles = {"BZM_Arcade_BERT_01_30", "BZM_Arcade_BERT_01_38"} }}
overlayMap["BZM_Arcade_BERT_01_23"] = {{ name = "other", tiles = {"BZM_Arcade_BERT_01_31", "BZM_Arcade_BERT_01_39"} }}
overlayMap["BZM_Bedroom_01_48"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_01_49"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_01_52"] = {{ name = "other", tiles = {"BZM_Bedroom_01_59", "BZM_Bedroom_01_58"} }}
overlayMap["BZM_Bedroom_01_53"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_01_56"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_01_57"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Bedroom_01_112"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_01_113"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_01_116"] = {{ name = "other", tiles = {"BZM_Bedroom_01_59", "BZM_Bedroom_01_58"} }}
overlayMap["BZM_Bedroom_01_117"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_01_120"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_01_121"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Bedroom_02_112"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_02_113"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_02_116"] = {{ name = "other", tiles = {"BZM_Bedroom_01_58", "BZM_Bedroom_01_59"} }}
overlayMap["BZM_Bedroom_02_117"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_02_120"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_02_121"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Bedroom_03_48"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_03_49"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_03_52"] = {{ name = "other", tiles = {"BZM_Bedroom_01_59", "BZM_Bedroom_01_58"} }}
overlayMap["BZM_Bedroom_03_53"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_03_56"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_03_57"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Bedroom_03_112"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_03_113"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_03_116"] = {{ name = "other", tiles = {"BZM_Bedroom_01_59", "BZM_Bedroom_01_58"} }}
overlayMap["BZM_Bedroom_03_117"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_03_120"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_03_121"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Bedroom_04_48"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_04_49"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_04_52"] = {{ name = "other", tiles = {"BZM_Bedroom_01_59", "BZM_Bedroom_01_58"} }}
overlayMap["BZM_Bedroom_04_53"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_04_56"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_04_57"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Bedroom_04_112"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_04_113"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_04_116"] = {{ name = "other", tiles = {"BZM_Bedroom_01_59", "BZM_Bedroom_01_58"} }}
overlayMap["BZM_Bedroom_04_117"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_04_120"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_04_121"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Bedroom_05_48"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_05_49"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_05_52"] = {{ name = "other", tiles = {"BZM_Bedroom_01_59", "BZM_Bedroom_01_58"} }}
overlayMap["BZM_Bedroom_05_53"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_05_56"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_05_57"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Bedroom_05_112"] = {{ name = "other", tiles = {"BZM_Bedroom_01_62", "BZM_Bedroom_01_63"} }}
overlayMap["BZM_Bedroom_05_113"] = {{ name = "other", tiles = {"BZM_Bedroom_01_122", "BZM_Bedroom_01_123"} }}
overlayMap["BZM_Bedroom_05_116"] = {{ name = "other", tiles = {"BZM_Bedroom_01_59", "BZM_Bedroom_01_58"} }}
overlayMap["BZM_Bedroom_05_117"] = {{ name = "other", tiles = {"BZM_Bedroom_01_61", "BZM_Bedroom_01_60"} }}
overlayMap["BZM_Bedroom_05_120"] = {{ name = "other", tiles = {"BZM_Bedroom_01_127", "BZM_Bedroom_01_126"} }}
overlayMap["BZM_Bedroom_05_121"] = {{ name = "other", tiles = {"BZM_Bedroom_01_125", "BZM_Bedroom_01_124"} }}
overlayMap["BZM_Location_Bar_01_74"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }}
overlayMap["BZM_Location_Bar_01_75"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }}
overlayMap["BZM_Location_Bar_01_76"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }}
overlayMap["BZM_Location_Bar_01_77"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }}
overlayMap["BZM_Location_Bar_01_78"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }}
overlayMap["BZM_Location_Bar_01_79"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }}
overlayMap["BZM_Shop_Shelves_0"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_8", "BZM_Shop_Shelves_4"} }}
overlayMap["BZM_Shop_Shelves_1"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_9", "BZM_Shop_Shelves_5"} }}
overlayMap["BZM_Shop_Shelves_2"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_10", "BZM_Shop_Shelves_6"} }}
overlayMap["BZM_Shop_Shelves_3"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_11", "BZM_Shop_Shelves_7"} }}
overlayMap["BZM_Shop_Shelves_16"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_24", "BZM_Shop_Shelves_32"} }}
overlayMap["BZM_Shop_Shelves_17"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_25", "BZM_Shop_Shelves_33"} }}
overlayMap["BZM_Shop_Shelves_18"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_26", "BZM_Shop_Shelves_34"} }}
overlayMap["BZM_Shop_Shelves_19"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_27", "BZM_Shop_Shelves_35"} }}
overlayMap["BZM_Shop_Shelves_20"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_28", "BZM_Shop_Shelves_36"} }}
overlayMap["BZM_Shop_Shelves_21"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_29", "BZM_Shop_Shelves_37"} }}
overlayMap["BZM_Shop_Shelves_22"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_30", "BZM_Shop_Shelves_38"} }}
overlayMap["BZM_Shop_Shelves_23"] = {{ name = "other", tiles = {"BZM_Shop_Shelves_31", "BZM_Shop_Shelves_39"} }}
overlayMap["BZM_ToddysOffence_24"] = {{ name = "other", tiles = {"BZM_ToddysOffence_8", "BZM_ToddysOffence_16"} }}
overlayMap["BZM_ToddysOffence_25"] = {{ name = "other", tiles = {"BZM_ToddysOffence_9", "BZM_ToddysOffence_17"} }}
overlayMap["BZM_ToddysOffence_26"] = {{ name = "other", tiles = {"BZM_ToddysOffence_10", "BZM_ToddysOffence_18"} }}
overlayMap["BZM_ToddysOffence_27"] = {{ name = "other", tiles = {"BZM_ToddysOffence_11", "BZM_ToddysOffence_19"} }}
overlayMap["BZM_ToddysOffence_28"] = {{ name = "other", tiles = {"BZM_ToddysOffence_12", "BZM_ToddysOffence_20"} }}
overlayMap["BZM_ToddysOffence_29"] = {{ name = "other", tiles = {"BZM_ToddysOffence_13", "BZM_ToddysOffence_21"} }}
overlayMap["BZM_ToddysOffence_30"] = {{ name = "other", tiles = {"BZM_ToddysOffence_14", "BZM_ToddysOffence_22"} }}
overlayMap["BZM_ToddysOffence_31"] = {{ name = "other", tiles = {"BZM_ToddysOffence_15", "BZM_ToddysOffence_23"} }}
overlayMap["BZM_ToddysOffence_40"] = {{ name = "other", tiles = {"BZM_ToddysOffence_48", "BZM_ToddysOffence_56"} }}
overlayMap["BZM_ToddysOffence_41"] = {{ name = "other", tiles = {"BZM_ToddysOffence_49", "BZM_ToddysOffence_57"} }}
overlayMap["BZM_ToddysOffence_44"] = {{ name = "other", tiles = {"BZM_ToddysOffence_52", "BZM_ToddysOffence_60"} }}
overlayMap["BZM_ToddysOffence_45"] = {{ name = "other", tiles = {"BZM_ToddysOffence_53", "BZM_ToddysOffence_61"} }}
overlayMap["BZM_Weed_Dispensery_0"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_8", "BZM_Weed_Dispensery_8"} }}
overlayMap["BZM_Weed_Dispensery_1"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_9", "BZM_Weed_Dispensery_9"} }}
overlayMap["BZM_Weed_Dispensery_2"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_10", "BZM_Weed_Dispensery_10"} }}
overlayMap["BZM_Weed_Dispensery_3"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_11", "BZM_Weed_Dispensery_11"} }}
overlayMap["BZM_Weed_Dispensery_4"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_12", "BZM_Weed_Dispensery_12"} }}
overlayMap["BZM_Weed_Dispensery_5"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_13", "BZM_Weed_Dispensery_13"} }}
overlayMap["BZM_Weed_Dispensery_6"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_14", "BZM_Weed_Dispensery_14"} }}
overlayMap["BZM_Weed_Dispensery_7"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_15", "BZM_Weed_Dispensery_15"} }}
overlayMap["BZM_Weed_Dispensery_34"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_38", "BZM_Weed_Dispensery_38"} }}
overlayMap["BZM_Weed_Dispensery_35"] = {{ name = "other", tiles = {"BZM_Weed_Dispensery_39", "BZM_Weed_Dispensery_39"} }}
overlayMap["BZMsBikerGarage01_5"] = {{ name = "other", tiles = {"BZMsBikerGarage01_20", "BZMsBikerGarage01_22"} }}
overlayMap["BZMsBikerGarage01_6"] = {{ name = "other", tiles = {"BZMsBikerGarage01_21", "BZMsBikerGarage01_23"} }}
overlayMap["BZMsBikerGarage01_80"] = {{ name = "other", tiles = {"BZMsBikerGarage01_82", "BZMsBikerGarage01_82"} }}
overlayMap["BZMsBikerGarage01_81"] = {{ name = "other", tiles = {"BZMsBikerGarage01_83", "BZMsBikerGarage01_83"} }}
overlayMap["location_restaurant_bar_01_64"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }}
overlayMap["location_restaurant_bar_01_65"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }}
overlayMap["location_restaurant_bar_01_66"] = {{ name = "other", tiles = {"food_01_78", "food_01_86"} }}
overlayMap["location_restaurant_bar_01_72"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }}
overlayMap["location_restaurant_bar_01_73"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }}
overlayMap["location_restaurant_bar_01_74"] = {{ name = "other", tiles = {"food_01_79", "food_01_87"} }}
overlayMap["location_shop_generic_01_53"] = {{ name = "other", tiles = {"clothing_02_14", "clothing_02_22"} }}
overlayMap["location_shop_generic_01_54"] = {{ name = "other", tiles = {"clothing_02_23", "clothing_02_15"} }}
overlayMap["location_shop_generic_01_56"] = {{ name = "other", tiles = {"clothing_02_32", "clothing_02_40"} }}
overlayMap["location_shop_generic_01_57"] = {{ name = "other", tiles = {"clothing_02_33", "clothing_02_41"} }}
overlayMap["location_shop_generic_01_58"] = {{ name = "other", tiles = {"clothing_02_34", "clothing_02_33"} }}
overlayMap["location_shop_generic_01_59"] = {{ name = "other", tiles = {"clothing_02_35", "clothing_02_43"} }}
overlayMap["location_shop_generic_01_60"] = {{ name = "other", tiles = {"clothing_02_36", "clothing_02_35"} }}
overlayMap["location_shop_generic_01_61"] = {{ name = "other", tiles = {"clothing_02_37", "clothing_02_45"} }}
overlayMap["location_shop_mallrats_01_56"] = {{ name = "other", tiles = {"location_shop_mallrats_01_64", "location_shop_mallrats_01_68"} }}
overlayMap["location_shop_mallrats_01_57"] = {{ name = "other", tiles = {"location_shop_mallrats_01_65", "location_shop_mallrats_01_69"} }}
overlayMap["location_shop_mallrats_01_58"] = {{ name = "other", tiles = {"location_shop_mallrats_01_66", "location_shop_mallrats_01_70"} }}
overlayMap["location_shop_mallrats_01_59"] = {{ name = "other", tiles = {"location_shop_mallrats_01_67", "location_shop_mallrats_01_71"} }}
overlayMap["location_shop_quickstop_02_0"] = {{ name = "other", tiles = {"books&misc_02_8", "books&misc_02_10"} }}
overlayMap["location_shop_quickstop_02_1"] = {{ name = "other", tiles = {"books&misc_02_9", "books&misc_02_11"} }}
overlayMap["location_shop_quickstop_02_6"] = {{ name = "other", tiles = {"food_02_0", "food_02_2"} }}
overlayMap["location_shop_quickstop_02_7"] = {{ name = "other", tiles = {"food_02_1", "food_02_3"} }}
overlayMap["location_shop_quickstop_02_8"] = {{ name = "other", tiles = {"food_02_8", "food_02_16"} }}
overlayMap["location_shop_quickstop_02_9"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["location_shop_quickstop_02_10"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["location_shop_quickstop_02_11"] = {{ name = "other", tiles = {"food_02_10", "food_02_18"} }}
overlayMap["location_shop_quickstop_02_12"] = {{ name = "other", tiles = {"food_02_11", "food_02_19"} }}
overlayMap["location_shop_quickstop_02_13"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["location_shop_quickstop_02_14"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["location_shop_quickstop_02_15"] = {{ name = "other", tiles = {"food_02_13", "food_02_21"} }}
overlayMap["location_shop_quickstop_02_24"] = {{ name = "other", tiles = {"books&misc_01_12", "books&misc_01_20"} }}
overlayMap["location_shop_quickstop_02_25"] = {{ name = "other", tiles = {"books&misc_01_13", "books&misc_01_21"} }}
overlayMap["location_shop_quickstop_02_26"] = {{ name = "other", tiles = {"books&misc_01_14", "books&misc_01_22"} }}
overlayMap["location_shop_quickstop_02_27"] = {{ name = "other", tiles = {"books&misc_01_15", "books&misc_01_23"} }}
overlayMap["location_shop_quickstop_02_40"] = {{ name = "other", tiles = {"location_shop_quickstop_02_49", "location_shop_quickstop_02_52"} }}
overlayMap["location_shop_quickstop_02_41"] = {{ name = "other", tiles = {"location_shop_quickstop_02_48", "location_shop_quickstop_02_53"} }}
overlayMap["location_shop_quickstop_02_42"] = {{ name = "other", tiles = {"location_shop_quickstop_02_50", "location_shop_quickstop_02_54"} }}
overlayMap["location_shop_quickstop_02_43"] = {{ name = "other", tiles = {"location_shop_quickstop_02_51", "location_shop_quickstop_02_55"} }}
overlayMap["location_shop_quickstop_02_64"] = {{ name = "other", tiles = {"food_01_49", "food_01_57"} }}
overlayMap["location_shop_quickstop_02_65"] = {{ name = "other", tiles = {"food_01_48", "food_01_56"} }}
overlayMap["location_shop_quickstop_02_66"] = {{ name = "other", tiles = {"food_01_50", "food_01_58"} }}
overlayMap["location_shop_quickstop_02_67"] = {{ name = "other", tiles = {"food_01_51", "food_01_59"} }}
overlayMap["location_shop_quickstop_02_68"] = {{ name = "other", tiles = {"food_01_52", "food_01_60"} }}
overlayMap["location_shop_quickstop_02_69"] = {{ name = "other", tiles = {"food_01_53", "food_01_61"} }}
overlayMap["location_shop_quickstop_02_72"] = {{ name = "other", tiles = {"books&misc_01_64", "books&misc_01_68"} }}
overlayMap["location_shop_quickstop_02_73"] = {{ name = "other", tiles = {"books&misc_01_65", "books&misc_01_69"} }}
overlayMap["location_shop_quickstop_02_74"] = {{ name = "other", tiles = {"books&misc_01_66", "books&misc_01_70"} }}
overlayMap["location_shop_quickstop_02_75"] = {{ name = "other", tiles = {"books&misc_01_67", "books&misc_01_71"} }}
overlayMap["location_shop_quickstop_02_80"] = {{ name = "other", tiles = {"food_01_72", "food_01_80"} }}
overlayMap["location_shop_quickstop_02_81"] = {{ name = "other", tiles = {"food_01_73", "food_01_81"} }}
overlayMap["location_shop_quickstop_02_82"] = {{ name = "other", tiles = {"food_01_74", "food_01_82"} }}
overlayMap["location_shop_quickstop_02_83"] = {{ name = "other", tiles = {"food_01_75", "food_01_83"} }}
overlayMap["location_shop_quickstop_02_84"] = {{ name = "other", tiles = {"food_01_76", "food_01_84"} }}
overlayMap["location_shop_quickstop_02_85"] = {{ name = "other", tiles = {"food_01_77", "food_01_85"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap