-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["pert_modern_stuff_01_6"] = {{ name = "other", tiles = {"pert_modern_stuff_01_7", "pert_modern_stuff_01_7"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
