objects = {
  { name = "", type = "ParkingStall", x = 13398, y = 6131, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13401, y = 6131, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13404, y = 6131, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13407, y = 6131, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "police", type = "ParkingStall", x = 13399, y = 6112, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "police", type = "ParkingStall", x = 13402, y = 6112, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "police", type = "ParkingStall", x = 13405, y = 6112, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "police", type = "ParkingStall", x = 13370, y = 6098, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "police", type = "ParkingStall", x = 13370, y = 6101, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "police", type = "ParkingStall", x = 13371, y = 6104, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "police", type = "ParkingStall", x = 13371, y = 6107, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "police", type = "ParkingStall", x = 13371, y = 6110, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "police", type = "ParkingStall", x = 13371, y = 6113, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "police", type = "ParkingStall", x = 13371, y = 6116, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "taxi", type = "ParkingStall", x = 13414, y = 6064, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13414, y = 6059, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13414, y = 6054, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13497, y = 6076, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13497, y = 6081, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13497, y = 6086, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6224, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6218, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6212, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6206, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6200, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6194, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6188, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6182, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6176, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13416, y = 6276, z = 0, width = 3, height = 7, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13416, y = 6269, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13436, y = 6246, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13442, y = 6246, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13448, y = 6246, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13477, y = 6246, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13485, y = 6246, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13496, y = 6223, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13496, y = 6216, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13496, y = 6207, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13496, y = 6201, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13496, y = 6188, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13496, y = 6182, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13496, y = 6175, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13496, y = 6169, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6041, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6047, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6058, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6064, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6095, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6101, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6107, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6113, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6119, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13497, y = 6125, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13458, y = 6201, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13458, y = 6207, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "taxi", type = "ParkingStall", x = 13458, y = 6213, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13458, y = 6191, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13458, y = 6185, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13458, y = 6179, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13458, y = 6173, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "Police", type = "ZombiesTypes", x = 13361, y = 6083, z = 0, width = 53, height = 60 },
  { name = "Prison", type = "ZombiesTypes", x = 13369, y = 6133, z = 0, width = 40, height = 8 },
  { name = "Factory", type = "ZombiesTypes", x = 13283, y = 6169, z = 0, width = 130, height = 46 },
  { name = "", type = "Forest", x = 13203, y = 6000, z = 0, width = 60, height = 15 },
  { name = "", type = "Forest", x = 13203, y = 6021, z = 0, width = 60, height = 279 },
  { name = "", type = "ParkingStall", x = 13634, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13637, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13640, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13631, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13625, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13619, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13616, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13610, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13607, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13604, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13601, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13595, y = 6046, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13663, y = 6046, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13658, y = 6046, z = 0, width = 4, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13667, y = 6040, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13667, y = 6035, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13667, y = 6030, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13667, y = 6020, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13572, y = 6064, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13572, y = 6057, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13572, y = 6050, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13572, y = 6043, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6220, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6214, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6202, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6196, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6184, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6262, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13635, y = 6247, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13642, y = 6246, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13636, y = 6236, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13629, y = 6237, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13601, y = 6236, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13594, y = 6237, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13597, y = 6247, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13604, y = 6246, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13516, y = 6247, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13523, y = 6247, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13516, y = 6235, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13523, y = 6235, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13537, y = 6264, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13537, y = 6274, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13537, y = 6257, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6264, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6271, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6278, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13538, y = 6221, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13538, y = 6214, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13538, y = 6207, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13538, y = 6197, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13538, y = 6190, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13538, y = 6183, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13538, y = 6176, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13538, y = 6169, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13692, y = 6221, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13692, y = 6214, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13692, y = 6196, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13692, y = 6189, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13692, y = 6182, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13692, y = 6175, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13692, y = 6168, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13675, y = 6247, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13682, y = 6246, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13679, y = 6235, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13673, y = 6237, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6263, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6270, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13687, y = 6059, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13691, y = 6059, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13695, y = 6064, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13699, y = 6059, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13703, y = 6064, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13517, y = 6126, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13521, y = 6126, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13525, y = 6126, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13529, y = 6126, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13533, y = 6126, z = 0, width = 3, height = 5 },
  { name = "", type = "ParkingStall", x = 13557, y = 6132, z = 0, width = 5, height = 3 },
  { name = "", type = "ParkingStall", x = 13557, y = 6128, z = 0, width = 5, height = 3 },
  { name = "", type = "ParkingStall", x = 13557, y = 6124, z = 0, width = 5, height = 3 },
  { name = "", type = "ParkingStall", x = 13557, y = 6120, z = 0, width = 5, height = 3 },
  { name = "", type = "ParkingStall", x = 13557, y = 6116, z = 0, width = 5, height = 3 },
  { name = "", type = "ParkingStall", x = 13557, y = 6112, z = 0, width = 5, height = 3 },
  { name = "", type = "ParkingStall", x = 13557, y = 6090, z = 0, width = 5, height = 3 },
  { name = "", type = "ParkingStall", x = 13557, y = 6086, z = 0, width = 5, height = 3 },
  { name = "Doctor", type = "ZombiesTypes", x = 13516, y = 6079, z = 0, width = 52, height = 64 },
  { name = "Doctor", type = "ZombiesTypes", x = 13568, y = 6079, z = 0, width = 7, height = 64 },
  { name = "FireDept", type = "ZombiesTypes", x = 13597, y = 6058, z = 0, width = 62, height = 15 },
  { name = "Gas2Go", type = "ZombiesTypes", x = 13679, y = 6016, z = 0, width = 45, height = 32 },
  { name = "", type = "Forest", x = 13741, y = 6000, z = 0, width = 59, height = 301 },
  { name = "", type = "ParkingStall", x = 13428, y = 6431, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6437, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6444, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6450, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6401, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6395, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6388, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6375, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6369, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6362, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6356, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6349, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6343, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6382, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6485, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6480, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6475, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6470, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6465, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6460, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6455, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6450, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6445, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6440, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6435, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6430, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13419, y = 6425, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6557, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6551, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6544, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6538, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6531, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6525, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6518, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6512, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6505, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6499, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6492, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6486, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6406, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6412, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6418, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6424, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6430, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13351, y = 6436, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13342, y = 6377, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13342, y = 6371, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13342, y = 6364, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13342, y = 6358, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13342, y = 6351, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13342, y = 6345, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6527, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6533, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6540, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6546, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6553, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6559, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6476, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6470, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13428, y = 6457, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "Baseball", type = "ZombiesTypes", x = 13471, y = 6515, z = 0, width = 23, height = 70 },
  { name = "Army", type = "ZombiesTypes", x = 13283, y = 6300, z = 0, width = 127, height = 19 },
  { name = "Army", type = "ZombiesTypes", x = 13411, y = 6300, z = 0, width = 82, height = 21 },
  { name = "CarRepair", type = "ZombiesTypes", x = 13415, y = 6347, z = 0, width = 7, height = 41 },
  { name = "", type = "Forest", x = 13203, y = 6300, z = 0, width = 60, height = 300 },
  { name = "", type = "ParkingStall", x = 13663, y = 6523, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13663, y = 6531, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13663, y = 6544, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13663, y = 6551, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13663, y = 6558, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13663, y = 6565, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13663, y = 6572, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13676, y = 6510, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13683, y = 6510, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "", type = "ParkingStall", x = 13584, y = 6524, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13584, y = 6530, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13584, y = 6537, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13584, y = 6543, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13584, y = 6550, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13584, y = 6556, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13584, y = 6563, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13584, y = 6569, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6522, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6529, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6546, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6557, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6570, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6483, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6476, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6469, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6462, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6454, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6447, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6440, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6397, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6390, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6375, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6368, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13544, y = 6360, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13572, y = 6394, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13572, y = 6388, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13572, y = 6382, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13585, y = 6397, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13585, y = 6391, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13585, y = 6384, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13585, y = 6377, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13585, y = 6364, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13585, y = 6357, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13575, y = 6438, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13575, y = 6445, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13575, y = 6452, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13575, y = 6459, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13575, y = 6466, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13575, y = 6473, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13575, y = 6480, z = 0, width = 3, height = 4, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6436, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6443, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6450, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6457, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6464, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6471, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6478, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6485, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6520, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6527, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6534, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6541, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6548, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6555, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6562, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6569, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6576, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6396, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6389, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6382, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6375, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6368, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6361, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6354, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13506, y = 6347, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6436, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6444, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6458, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6465, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6472, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6479, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6348, z = 0, width = 3, height = 6, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6360, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6368, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6375, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13693, y = 6387, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6484, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6477, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6470, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6462, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6455, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6448, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6439, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6572, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6565, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6554, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6547, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6540, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6531, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6524, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6398, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6391, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6380, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6372, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6365, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13622, y = 6352, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "", type = "ParkingStall", x = 13653, y = 6569, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13653, y = 6563, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13653, y = 6556, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13653, y = 6550, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13653, y = 6543, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13653, y = 6537, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13653, y = 6530, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "", type = "ParkingStall", x = 13653, y = 6524, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "Army", type = "ZombiesTypes", x = 13673, y = 6520, z = 0, width = 63, height = 26 },
  { name = "Army", type = "ZombiesTypes", x = 13706, y = 6537, z = 0, width = 24, height = 49 },
  { name = "Army", type = "ZombiesTypes", x = 13689, y = 6547, z = 0, width = 22, height = 13 },
  { name = "School", type = "ZombiesTypes", x = 13664, y = 6565, z = 0, width = 39, height = 23 },
  { name = "School", type = "ZombiesTypes", x = 13664, y = 6548, z = 0, width = 24, height = 17 },
  { name = "Army", type = "ZombiesTypes", x = 13511, y = 6301, z = 0, width = 217, height = 20 },
  { name = "", type = "Forest", x = 13741, y = 6300, z = 0, width = 59, height = 300 }
}
